# Generated by Django 2.2.5 on 2024-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Nut', 'Nut'), ('Dal', 'Dal'), ('Meat', 'Meat')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Products')),
            ],
        ),
    ]
